<!--
  ChatView — structured transcript viewer styled like Claude.ai chat.

  Subscribes to GET /api/sessions/:sid/transcript?since=0 (SSE, event "transcript")
  and groups TranscriptEvents into ChatTurns for display.

  Props: session: SessionMeta | null
-->
<script lang="ts">
  import { marked } from 'marked';
  import DOMPurify from 'dompurify';
  import { isTauri, invokeCommand } from '$lib/tauri';
  import {
    api,
    type SessionMeta,
    type TranscriptEvent,
    type TranscriptUsage
  } from '$lib/api/client';
  import { subscribeSSE, type SSEHandle } from '$lib/api/sse';
  import { Bot, Send, ChevronDown, ChevronUp, Wrench, Paperclip } from '$lib/icons';
  import { toast } from 'svelte-sonner';

  interface Props {
    session: SessionMeta | null;
  }

  let { session }: Props = $props();

  // ---- Types ----------------------------------------------------------------

  type ToolBlock = {
    id: string;
    name: string;
    args: unknown;
    result?: unknown;
    isError: boolean;
    expanded: boolean;
  };

  type ChatTurn = {
    id: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    thinking?: string;
    toolBlocks: ToolBlock[];
    isStreaming: boolean;
    renderedHtml: string; // empty while streaming; populated once when isStreaming→false
    model?: string;
    source?: string;
    usage?: TranscriptUsage;
  };

  // ---- State ----------------------------------------------------------------

  let turns = $state<ChatTurn[]>([]);
  let input = $state('');
  let sending = $state(false);
  let textareaEl: HTMLTextAreaElement | null = $state(null);
  let scrollEl: HTMLDivElement | null = $state(null);

  // Scroll batching (Fix 2)
  let scrollPending = false;

  // Event queue for batched RAF processing (Fix 3)
  let eventQueue: TranscriptEvent[] = [];
  let flushPending = false;

  // Last received seq for reconnect tracking (Fix 4)
  let lastSeq = 0;
  let renderingTurnIds = new Set<string>();

  const encoder = new TextEncoder();

  const stopped = $derived(!session || session.status !== 'running');

  // ---- Markdown helper ------------------------------------------------------

  async function renderMarkdown(text: string): Promise<string> {
    if (isTauri) {
      // Native Rust via Tauri IPC — zero JS overhead, no DOMPurify needed
      // (HTML is generated by pulldown-cmark from trusted markdown input)
      return invokeCommand<string>('parse_markdown', { text });
    }
    // Browser fallback (dev server / pnpm dev)
    const html = marked.parse(text, { breaks: true, gfm: true });
    return DOMPurify.sanitize(typeof html === 'string' ? html : '');
  }

  // ---- Turn processing ------------------------------------------------------

  function lastAssistantTurn(): ChatTurn | null {
    for (let i = turns.length - 1; i >= 0; i--) {
      if (turns[i].role === 'assistant') return turns[i];
    }
    return null;
  }

  function processEvent(ev: TranscriptEvent) {
    if (ev.kind === 'meta') return;

    if (ev.kind === 'system_note') {
      turns.push({
        id: String(ev.seq),
        role: 'system',
        content: ev.content ?? ev.subtype ?? 'system note',
        toolBlocks: [],
        isStreaming: false,
        renderedHtml: ''
      });
      return;
    }

    if (ev.kind === 'message') {
      if (ev.role === 'user') {
        turns.push({
          id: String(ev.seq),
          role: 'user',
          content: ev.content ?? '',
          toolBlocks: [],
          isStreaming: false,
          renderedHtml: ''
        });
      } else if (ev.role === 'assistant') {
        let last = lastAssistantTurn();
        if (!last) {
          last = {
            id: String(ev.seq),
            role: 'assistant',
            content: '',
            toolBlocks: [],
            isStreaming: true,
            renderedHtml: '',
            model: ev.model ?? undefined,
            source: ev.source,
            usage: ev.usage ?? undefined
          };
          turns.push(last);
        }
        last.content += ev.content ?? '';
        if (ev.model) last.model = ev.model;
        if (ev.usage) last.usage = ev.usage;
      }
      return;
    }

    if (ev.kind === 'thinking') {
      let last = lastAssistantTurn();
      if (!last) {
        last = {
          id: String(ev.seq),
          role: 'assistant',
          content: '',
          toolBlocks: [],
          isStreaming: true,
          renderedHtml: '',
          source: ev.source
        };
        turns.push(last);
      }
      last.thinking = (last.thinking ?? '') + (ev.content ?? '');
      return;
    }

    if (ev.kind === 'tool_call') {
      let last = lastAssistantTurn();
      if (!last) {
        last = {
          id: String(ev.seq),
          role: 'assistant',
          content: '',
          toolBlocks: [],
          isStreaming: true,
          renderedHtml: '',
          source: ev.source
        };
        turns.push(last);
      }
      last.toolBlocks.push({
        id: ev.tool_use_id ?? String(ev.seq),
        name: ev.tool_name ?? '(unknown)',
        args: ev.tool_args,
        isError: false,
        expanded: true
      });
      return;
    }

    if (ev.kind === 'tool_result') {
      const toolId = ev.tool_use_id;
      if (toolId) {
        for (const turn of turns) {
          const block = turn.toolBlocks.find((b) => b.id === toolId);
          if (block) {
            block.result = ev.tool_result;
            block.isError = ev.is_error ?? false;
            block.expanded = block.isError;
            break;
          }
        }
      }
      return;
    }
  }

  // ---- Streaming state sync -------------------------------------------------

  $effect(() => {
    const state = session?.detected_state ?? null;
    const isWorking = state === 'working';

    // Collect all completed assistant turns that still need HTML rendering
    const pending = turns.filter(
      (t) =>
        t.role === 'assistant' &&
        !t.isStreaming &&
        t.content &&
        !t.renderedHtml &&
        !renderingTurnIds.has(t.id)
    );

    if (pending.length > 1 && isTauri) {
      // Batch path: rayon renders all in parallel in one IPC roundtrip
      for (const turn of pending) renderingTurnIds.add(turn.id);
      void invokeCommand<string[]>('parse_markdown_batch', {
        texts: pending.map((t) => t.content)
      })
        .then((htmls) => {
          htmls.forEach((html, i) => {
            pending[i].renderedHtml = html;
          });
        })
        .finally(() => {
          for (const turn of pending) renderingTurnIds.delete(turn.id);
        });
    } else {
      // Single or browser fallback
      for (const turn of pending) {
        renderingTurnIds.add(turn.id);
        void renderMarkdown(turn.content)
          .then((html) => {
            turn.renderedHtml = html;
          })
          .finally(() => {
            renderingTurnIds.delete(turn.id);
          });
      }
    }

    // Sync isStreaming flags
    for (const turn of turns) {
      if (turn.role === 'assistant') {
        turn.isStreaming = isWorking && turn === lastAssistantTurn();
      }
    }
    if (isWorking) {
      const last = lastAssistantTurn();
      if (last) last.isStreaming = true;
    }
  });

  // ---- SSE subscription -----------------------------------------------------

  let sseHandle: SSEHandle | null = null;

  function openSSE(sessionId: string) {
    closeSSE();
    turns = [];
    renderingTurnIds = new Set();
    lastSeq = 0;
    eventQueue = [];
    sseHandle = subscribeSSE(`/sessions/${sessionId}/transcript?since=0`, () => {}, {
      reconnect: true,
      events: {
        transcript: (data) => {
          const ev = data as TranscriptEvent;
          if (ev.seq > lastSeq) lastSeq = ev.seq;
          enqueueEvent(ev);
        }
      }
    });
  }

  function closeSSE() {
    sseHandle?.close();
    sseHandle = null;
  }

  $effect(() => {
    const sid = session?.id;
    if (sid) {
      openSSE(sid);
    } else {
      closeSSE();
      turns = [];
    }
    return () => {
      closeSSE();
    };
  });

  // ---- Auto-scroll (Fix 2: collapse all scroll requests into one RAF frame) --

  function scheduleScroll() {
    if (scrollPending) return;
    scrollPending = true;
    requestAnimationFrame(() => {
      scrollPending = false;
      if (!scrollEl) return;
      const { scrollTop, scrollHeight, clientHeight } = scrollEl;
      const distFromBottom = scrollHeight - scrollTop - clientHeight;
      // Only auto-scroll when the user is already near the bottom
      if (distFromBottom < 120) {
        scrollEl.scrollTop = scrollEl.scrollHeight;
      }
    });
  }

  // ---- Event queue (Fix 3: batch burst events into a single RAF flush) ------

  function enqueueEvent(ev: TranscriptEvent) {
    eventQueue.push(ev);
    if (flushPending) return;
    flushPending = true;
    requestAnimationFrame(() => {
      flushPending = false;
      const batch = eventQueue.splice(0);
      for (const e of batch) processEvent(e);
      scheduleScroll();
    });
  }

  // ---- Input handling -------------------------------------------------------

  async function sendInput() {
    if (!session || !input.trim() || sending || stopped) return;
    sending = true;
    const payload = input;
    input = '';
    try {
      await api.sessions.input(session.id, encoder.encode(payload));
      await new Promise((r) => setTimeout(r, 60));
      await api.sessions.input(session.id, encoder.encode('\r'));
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      toast.error(`Send failed: ${msg}`);
    } finally {
      sending = false;
    }
  }

  function onKeydown(ev: KeyboardEvent) {
    if (ev.key === 'Enter' && !ev.shiftKey) {
      ev.preventDefault();
      void sendInput();
    }
  }

  function onTextareaInput() {
    if (!textareaEl) return;
    textareaEl.style.height = 'auto';
    const lineHeight = 20;
    const maxHeight = lineHeight * 4 + 20;
    textareaEl.style.height = Math.min(textareaEl.scrollHeight, maxHeight) + 'px';
  }

  // ---- Thinking block toggle ------------------------------------------------

  let thinkingExpanded = $state<Record<string, boolean>>({});

  function toggleThinking(turnId: string, streaming: boolean) {
    thinkingExpanded[turnId] = !(thinkingExpanded[turnId] ?? streaming);
  }

  function isThinkingExpanded(turnId: string, streaming: boolean): boolean {
    if (turnId in thinkingExpanded) return thinkingExpanded[turnId];
    return streaming;
  }

  // ---- JSON pretty print ----------------------------------------------------

  function prettyJson(val: unknown): string {
    try {
      return JSON.stringify(val, null, 2);
    } catch {
      return String(val);
    }
  }
</script>

<div class="flex h-full flex-col overflow-hidden" style="background: var(--surface-canvas);">
  <!-- Message list -->
  <div
    class="min-h-0 flex-1 overflow-y-auto py-6"
    style="transform: translateZ(0); will-change: scroll-position;"
    bind:this={scrollEl}
  >
    {#if !session}
      <!-- No session selected -->
      <div class="flex h-full flex-col items-center justify-center gap-2 text-center">
        <p class="text-sm" style="color: var(--fg-muted);">
          Select a session to view the transcript.
        </p>
      </div>
    {:else if turns.length === 0}
      <!-- Empty state -->
      <div class="flex h-full flex-col items-center justify-center gap-2 text-center">
        <Bot size={28} style="color: var(--fg-muted); opacity: 0.4;" />
        <p class="text-sm" style="color: var(--fg-muted);">
          {#if session.has_transcript === false}
            No hay transcript aún — el agente generará el historial de conversación automáticamente.
          {:else}
            Waiting for transcript events…
          {/if}
        </p>
      </div>
    {:else}
      <div class="mx-auto max-w-[820px] px-5 sm:px-7">
        {#each turns as turn (turn.id)}
          {#if turn.role === 'user'}
            <!-- User turn -->
            <div
              class="chat-turn mb-8"
              style="contain: content; content-visibility: auto; contain-intrinsic-size: 80px;"
            >
              <div class="mb-2 flex items-center gap-2">
                <span class="text-xs font-semibold" style="color: var(--fg-muted);">You</span>
              </div>
              <div class="chat-user-text text-sm whitespace-pre-wrap break-words leading-7">
                {turn.content}
              </div>
            </div>
          {:else if turn.role === 'assistant'}
            <!-- Assistant turn -->
            <div
              class="chat-turn mb-9"
              style="contain: content; content-visibility: auto; contain-intrinsic-size: 220px;"
            >
              <div class="mb-2 flex min-w-0 flex-wrap items-center gap-2">
                <span class="text-xs font-semibold" style="color: var(--accent);">Agent</span>
                {#if turn.model}
                  <span
                    class="rounded px-1.5 py-0.5 font-mono text-[10px]"
                    style="background: var(--surface-window); color: var(--fg-muted); border: 1px solid var(--border-subtle);"
                  >
                    {turn.model}
                  </span>
                {:else if turn.source}
                  <span class="font-mono text-[10px]" style="color: var(--fg-muted);">
                    {turn.source}
                  </span>
                {/if}
              </div>

              <div class="min-w-0">
                <!-- Thinking block -->
                {#if turn.thinking}
                  {@const expanded = isThinkingExpanded(turn.id, turn.isStreaming)}
                  <div
                    class="mb-3 overflow-hidden rounded-md border"
                    style="border-color: var(--border-subtle);"
                  >
                    <button
                      type="button"
                      onclick={() => toggleThinking(turn.id, turn.isStreaming)}
                      class="flex w-full items-center gap-1.5 px-3 py-1.5 text-xs font-medium italic"
                      style="color: var(--fg-muted);"
                    >
                      {#if expanded}
                        <ChevronUp size={12} />
                      {:else}
                        <ChevronDown size={12} />
                      {/if}
                      Thinking
                      {#if turn.isStreaming && !turn.content}
                        <span
                          class="ml-1 inline-block h-1.5 w-1.5 rounded-full animate-pulse"
                          style="background: var(--accent);"
                        ></span>
                      {/if}
                    </button>
                    {#if expanded}
                      <div
                        class="border-t px-3 py-2 text-xs italic"
                        style="border-color: var(--border-subtle); color: var(--fg-muted); white-space: pre-wrap; word-break: break-word;"
                      >
                        {turn.thinking}
                      </div>
                    {/if}
                  </div>
                {/if}

                <!-- Tool call blocks -->
                {#each turn.toolBlocks as block (block.id)}
                  <div
                    class="mb-3 overflow-hidden rounded-md border"
                    style="border-color: var(--border-subtle);"
                  >
                    <button
                      type="button"
                      onclick={() => {
                        block.expanded = !block.expanded;
                      }}
                      class="flex w-full items-center gap-1.5 px-3 py-1.5 text-xs font-medium font-mono"
                      style="color: var(--fg-muted);"
                    >
                      <Wrench size={12} />
                      <span class="flex-1 text-left" style="color: var(--fg-default);"
                        >{block.name}</span
                      >
                      {#if block.expanded}
                        <ChevronUp size={12} />
                      {:else}
                        <ChevronDown size={12} />
                      {/if}
                    </button>
                    {#if block.expanded}
                      <div class="border-t" style="border-color: var(--border-subtle);">
                        <!-- Args -->
                        <pre
                          class="overflow-x-auto px-3 py-2 text-[11px] font-mono"
                          style="background: var(--surface-window); color: var(--fg-muted); white-space: pre-wrap; word-break: break-word;">{prettyJson(
                            block.args
                          )}</pre>
                        <!-- Result (if available) -->
                        {#if block.result !== undefined}
                          <div
                            class="border-t px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wide"
                            style="border-color: var(--border-subtle); color: {block.isError
                              ? '#f87171'
                              : 'var(--fg-muted)'};"
                          >
                            {block.isError ? 'Error' : 'Result'}
                          </div>
                          <pre
                            class="overflow-x-auto px-3 py-2 text-[11px] font-mono"
                            style="background: var(--surface-window); color: {block.isError
                              ? '#fca5a5'
                              : 'var(--fg-muted)'}; white-space: pre-wrap; word-break: break-word;">{prettyJson(
                              block.result
                            )}</pre>
                        {/if}
                      </div>
                    {/if}
                  </div>
                {/each}

                <!-- Main content: raw text while streaming, rendered HTML when done -->
                {#if turn.content}
                  {#if turn.renderedHtml}
                    <!-- Completed turn: safe rendered markdown -->
                    <div
                      class="chat-prose max-w-none leading-relaxed"
                      style="color: var(--fg-default);"
                    >
                      <!-- eslint-disable-next-line svelte/no-at-html-tags -->
                      {@html turn.renderedHtml}
                    </div>
                  {:else}
                    <!-- Streaming turn: raw text, no markdown parse overhead -->
                    <p
                      class="chat-streaming-text text-sm whitespace-pre-wrap break-words leading-7"
                      style="color: var(--fg-default);"
                    >
                      {turn.content}
                    </p>
                  {/if}
                {/if}

                <!-- Streaming cursor -->
                {#if turn.isStreaming && !turn.content && !turn.thinking && turn.toolBlocks.length === 0}
                  <span
                    class="inline-block w-2 h-4 animate-pulse opacity-70"
                    style="background: var(--fg-default);"
                  ></span>
                {/if}

                <!-- Usage badge -->
                {#if turn.usage}
                  <div class="mt-3 flex flex-wrap gap-2">
                    {#if turn.usage.input_tokens != null}
                      <span
                        class="rounded px-1.5 py-0.5 font-mono text-[10px]"
                        style="background: var(--surface-window); color: var(--fg-muted); border: 1px solid var(--border-subtle);"
                      >
                        in {turn.usage.input_tokens}
                      </span>
                    {/if}
                    {#if turn.usage.output_tokens != null}
                      <span
                        class="rounded px-1.5 py-0.5 font-mono text-[10px]"
                        style="background: var(--surface-window); color: var(--fg-muted); border: 1px solid var(--border-subtle);"
                      >
                        out {turn.usage.output_tokens}
                      </span>
                    {/if}
                  </div>
                {/if}
              </div>
            </div>
          {:else}
            <!-- System turn — centered pill -->
            <div
              class="my-2 flex justify-center"
              style="contain: content; content-visibility: auto; contain-intrinsic-size: 32px;"
            >
              <span
                class="rounded-full px-3 py-1 text-xs"
                style="background: var(--surface-window); color: var(--fg-muted); border: 1px solid var(--border-subtle);"
              >
                {turn.content}
              </span>
            </div>
          {/if}
        {/each}
      </div>
    {/if}
  </div>

  <!-- Chat input footer -->
  <div
    class="shrink-0 border-t px-4 py-4"
    style="background: var(--surface-window); border-color: var(--border-subtle);"
  >
    <div
      class="rounded-xl border"
      style="background: var(--surface-canvas); border-color: var(--border-subtle);"
    >
      <!-- Textarea row -->
      <div class="px-4 pt-3 pb-1">
        <textarea
          bind:this={textareaEl}
          bind:value={input}
          onkeydown={onKeydown}
          oninput={onTextareaInput}
          placeholder={stopped ? 'Session not running' : 'Message the agent…'}
          disabled={stopped}
          rows={2}
          class="w-full resize-none bg-transparent text-sm outline-none placeholder:opacity-40 disabled:cursor-not-allowed"
          style="color: var(--fg-default); font-size: 0.875rem; line-height: 1.6; max-height: 120px; overflow-y: auto;"
        ></textarea>
      </div>
      <!-- Action bar: attach left, send right -->
      <div class="flex items-center justify-between px-3 pb-3">
        <button
          type="button"
          disabled={stopped}
          class="flex h-8 w-8 items-center justify-center rounded-lg transition-colors hover:opacity-80 disabled:opacity-30"
          style="color: var(--fg-muted);"
          title="Attach file"
          aria-label="Attach file"
        >
          <Paperclip size={16} />
        </button>
        <button
          type="button"
          onclick={() => void sendInput()}
          disabled={sending || stopped || !input.trim()}
          class="flex h-8 w-8 items-center justify-center rounded-xl transition-all disabled:opacity-30 hover:opacity-90 active:scale-95"
          style="background: var(--accent); color: white;"
          title="Send (Enter)"
          aria-label="Send"
        >
          <Send size={14} />
        </button>
      </div>
    </div>
  </div>
</div>

<style>
  .chat-turn {
    color: var(--fg-default);
  }

  .chat-user-text,
  .chat-streaming-text {
    color: var(--fg-default);
    max-width: 72ch;
  }

  .chat-prose {
    font-size: 0.9rem;
    line-height: 1.75;
  }

  :global(.chat-prose > :first-child) {
    margin-top: 0;
  }

  :global(.chat-prose > :last-child) {
    margin-bottom: 0;
  }

  :global(.chat-prose h1),
  :global(.chat-prose h2),
  :global(.chat-prose h3),
  :global(.chat-prose h4) {
    color: var(--fg-default);
    letter-spacing: 0;
    line-height: 1.25;
  }

  :global(.chat-prose h1) {
    font-size: 1.35rem;
    margin-top: 1.4em;
    margin-bottom: 0.6em;
  }

  :global(.chat-prose h2) {
    font-size: 1.15rem;
    margin-top: 1.3em;
    margin-bottom: 0.55em;
  }

  :global(.chat-prose h3) {
    font-size: 1rem;
    margin-top: 1.2em;
    margin-bottom: 0.45em;
  }

  :global(.chat-prose p),
  :global(.chat-prose ul),
  :global(.chat-prose ol),
  :global(.chat-prose blockquote),
  :global(.chat-prose pre),
  :global(.chat-prose table) {
    margin-top: 0.7em;
    margin-bottom: 0.7em;
  }

  :global(.chat-prose a) {
    color: var(--accent);
    text-decoration: underline;
    text-underline-offset: 3px;
  }

  :global(.chat-prose ul),
  :global(.chat-prose ol) {
    padding-left: 1.25rem;
  }

  :global(.chat-prose li + li) {
    margin-top: 0.25rem;
  }

  :global(.chat-prose blockquote) {
    border-left: 3px solid var(--border-subtle);
    color: var(--fg-muted);
    padding-left: 1rem;
    font-style: normal;
  }

  :global(.chat-prose pre) {
    background: var(--surface-window);
    border: 1px solid var(--border-subtle);
    border-radius: 6px;
    color: var(--fg-default);
    overflow-x: auto;
    padding: 0.85rem 1rem;
  }

  :global(.chat-prose pre code) {
    background: transparent;
    border: 0;
    padding: 0;
    font-size: 0.82rem;
    line-height: 1.65;
  }

  :global(.chat-prose code:not(pre code)) {
    background: var(--surface-window);
    border: 1px solid var(--border-subtle);
    border-radius: 4px;
    color: var(--fg-default);
    font-size: 0.84em;
    padding: 0.08rem 0.28rem;
  }

  :global(.chat-prose table) {
    border-collapse: collapse;
    display: block;
    max-width: 100%;
    overflow-x: auto;
  }

  :global(.chat-prose th),
  :global(.chat-prose td) {
    border: 1px solid var(--border-subtle);
    padding: 0.45rem 0.6rem;
  }

  :global(.chat-prose th) {
    background: var(--surface-window);
    color: var(--fg-default);
    font-weight: 600;
  }
</style>
